language: c

dist: focal

addons:
  apt:
    packages:
      - doxygen
      - clang-tidy
      - cmake

script:
  - /usr/bin/cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  - /usr/bin/cmake --build build -j 4 --target all check install docs
  - cd build
  - ls -R /usr/lib
  - run-clang-tidy
